Docs: update json schemas
qgis-deployment/qgis-deployment-toolbelt-cli pull request #559
Opened 2024-09-18 05:25 UTC by Guts

2024-12-06 12:08 UTC, jmkerloch requested changes

2024-12-06 12:08 UTC, jmkerloch commented on docs/schemas/scenario/jobs/qdt_job_base.json
> +  "$id": "https://raw.githubusercontent.com/Guts/qgis-deployment-cli/main/docs/schemas/scenario/jobs/qdt_job_base.json",
Should replace Guts by qgis-deployment

2024-12-12 09:00 UTC, Guts reviewed
OK, let's cut this one in smaller parts.

2024-12-12 10:32 UTC, jmkerloch approved these changes
Let's merge to test on main branch !

2024-12-12 10:32 UTC, merged